### PR TITLE
MB Data from universalis

### PR DESCRIPTION
**Pull request by Rennerdo30**
This is a very simple implementation of live marketboard data from universalis.
Data will be cached in config folder as json.
JSON data will be valid for 24h then the item will be refreshed. 

image

image

Added Config-Option for tooltip
image

### CODE REVIEW

**Review by Critical-Impact — CHANGES_REQUESTED** [review]
Thank you so much for making this, it works really well and I definitely can see how useful this will be.
I have found a few minor issues, and I figured I'd bring them up to see if you wanted to fix them or if you wanted me to address them.

1) It appears that when the character is logging in and doesn't have a valid LocalPlayer a call to GetMarketBoardData can still occur. This is most likely there is a short delay between when Dalamud says the character is logged in and the LocalPlayer class is filled.
Error was
```
17:56:15.016 | ERR ["InventoryTools"] UiBuilder OnBuildUi caught exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at InventoryTools.MarketBoard.Universalis.GetMarketBoardData(UInt32 itemId)
   at InventoryTools.MarketBoard.Universalis.GetMarketBoardData(InventoryItem item)
   at InventoryTools.Logic.MarketBoardPriceColumn.Value(InventoryItem item)
   at InventoryTools.Logic.MarketBoardPriceColumn.Draw(SortingResult item)
   at InventoryTools.Logic.FilterTable.Draw()
   at InventoryTools.InventoryToolsUi.Draw()
```

Should just be a matter of checking to see if Service.ClientState.LocalPlayer is null or not.

2) I have a lot of items and with 8 retainers that are all basically full that equals a lot of requests to Universalis when the plugin first loads. I don't see an issue with that per-say, however I think it might be wise to save the cached market data for X amount of time(X being something user configurable perhaps). That way when they reload the plugin/game they'll have the existing prices still available.

3) When determining if a item should be priced against Universalis, you have used CanBeBought
We probably need to make a new boolean inside InventoryItem called "CanBeTraded" and have it return !Item.IsUntradeable (along side some null checking)
I believe every item that can be traded can be put on the market board but I can't say that for sure.

4) Love the feature with the tooltips, I think only thing I can suggest there is that we make it so it can be toggled on/off.

5) With the tooltips, it just needs a tweak to say which "Source" it's in, be it a retainer or a player and their name

Apart from that, very much appreciate the work :)

**Comment by Rennerdo30** [comment]
Thanks for your feedback!
All your points are valid and I will have a look at them.

**Comment by Rennerdo30** [comment]
* Tooltip is now a toggle option in config
* Cache with 24h lifetime per item
* untradable will now be read from excel

image

**Comment by Critical-Impact** [comment]
Have merged, will do some more tests and make a few tweaks and will get a new test out build either today or tomorrow :)

**Pull request merged**
